[package]
name = "scrape-gltf-loader"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gltf = "1.3.0"
thiserror = "1.0.50"

[dependencies.bevy_math]
version = "0.11.3"
default-features = false
